### ISSUE TITLE
Ability to sort uploaded pictures

### ISSUE THREAD

**Issue by ArCoLab** [Matvik/yii2-model-gallery#5]
The ability to change the order of the images directly from the AJAX form using drag and drop with the mouse is very much lacking.
I see that there is a `priority` field in migration...

**Comment by Matvik** [comment]
You can do this. Saves, deletes, and reorders images is doing immediately in Ajax form.

**Comment by ArCoLab** [comment]
I'm not getting the sorting of drag and drop images to work. Maybe some JS connection is missing?

**Comment by Matvik** [comment]
Can you provide demo for this?

**Comment by ArCoLab** [comment]
Sorting doesn't work when loading a form in bottstrap popup modal window.

**Comment by Matvik** [comment]
Created new Yii 2 basic project and tested Ajax widget in Bootstrap 5 modal, drag and drop works fine. 
It uses yiisoft/yii2-jui (Jquery UI) package for drag-n-drop, maybe it`s some bug with this library in your project.
Check browser console output for JUI errors
